### ISSUE TITLE
None of the Items are working in my Modpack

### ISSUE THREAD

**Issue by yuma-dev** [maybejake/Jakes-Build-Tools#1]
Items are craftable, but do not show up in EMI and when crafted they do nothing.
Also had vanilla refresh that stopped working after a while, might be an Issue on my end but I can't pinpoint what exactly the issue would be 
Here is the latest log from my Server:
https://mclo.gs/2kCvv2G

**Comment by maybejake** [comment]
As this is a datapack ported to a mod, there is sadly no possibility for EMI/REI/JEI support

However! I can help with the items not working, looking at your server logs I can see the following:
```
[09:39:33] [main/ERROR]: Couldn't load tag minecraft:tick as it is missing following references: craftableshell:tick (from file/craftable-shulker-shells-1-21.zip)
[09:39:33] [main/ERROR]: Couldn't load tag minecraft:load as it is missing following references: craftableshell:load (from file/craftable-shulker-shells-1-21.zip)

There seems to be some kind of issue with `craftable-shulker-shells-1-21.zip` and its breaking the tick and load functions in minecraft. Without these, most datapacks will fail to work

I suggest either removing that datapack or checking to see if the version you have installed is compatible with your version of minecraft

**Comment by maybejake** [comment]
If it's a recipe that uses vanilla items to produce a vanilla item, I recommend any of the many recipe datapack generators out there!

This one is very good: https://misode.github.io/recipe/
